version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: restful_api_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Z5*u38hv1
      MYSQL_DATABASE: gmsky_dev-test
      MYSQL_USER: gmsky_admin
      MYSQL_PASSWORD: Z5*u38hv1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: